apiVersion: v1
kind: Secret
metadata:
  name: {{ include "camp.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "camp.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.secrets.secretKey | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  DEFAULT_PASSWORD: {{ .Values.secrets.defaultPassword | b64enc | quote }}
